import asyncio
import os
import logging
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field
from agents.base import BaseAgent, AgentResult
from agents.registry import registry

class DeploymentInput(BaseModel):
    temp_file_path: str = Field(..., description="The path to the temporary agent file generated by CodeGenAgent.")
    agent_class_name: str = Field(..., description="The name of the agent class to deploy.")
    approved: bool = Field(False, description="Whether the user has approved this deployment.")

class DeploymentAgent(BaseAgent):
    name = "deployment_agent"
    description = "Handles the auditing, moving, and hot-loading of dynamically generated agents."
    input_schema = DeploymentInput

    def __init__(self, orchestrator=None):
        super().__init__()
        self.orchestrator = orchestrator

    async def run(self, params: DeploymentInput, chat_id: str) -> AgentResult:
        if not params.approved:
            return AgentResult(
                status="NEED_INFO",
                message=f"Deployment of {params.agent_class_name} requires user approval. Please review the code at {params.temp_file_path} and call me with approved=True."
            )

        if not os.path.exists(params.temp_file_path):
            return AgentResult(status="FAILED", message=f"Temp file {params.temp_file_path} not found.")

        try:
            # 1. Move to permanent directory
            dest_dir = "/etc/myapp/genie/src/agents/dynamic"
            os.makedirs(dest_dir, exist_ok=True)
            # Create __init__.py if it doesn't exist
            if not os.path.exists(os.path.join(dest_dir, "__init__.py")):
                with open(os.path.join(dest_dir, "__init__.py"), "w") as f:
                    pass

            dest_file_name = f"{params.agent_class_name.lower()}.py"
            dest_path = os.path.join(dest_dir, dest_file_name)
            
            import shutil
            shutil.copy(params.temp_file_path, dest_path)
            self.logger.info(f"Copied {params.temp_file_path} to {dest_path}")

            # 2. Dynamic Loading
            # We need to pass dependencies that the dynamic agent might need.
            # Usually these are 'orchestrator' or 'redis_mgr'.
            # For simplicity, we'll try to guess what it needs or just pass common ones.
            
            # Note: We need to ensure these are available in the current context
            # In a real system, we'd have a more formal dependency injection.
            
            kwargs = {}
            if self.orchestrator:
                kwargs['orchestrator'] = self.orchestrator
            
            # Try to load and register
            registry.load_agent_from_file(dest_path, params.agent_class_name, **kwargs)

            return AgentResult(
                status="SUCCESS",
                data={"agent_name": params.agent_class_name.lower(), "permanent_path": dest_path},
                message=f"Agent {params.agent_class_name} has been successfully deployed and hot-loaded!"
            )

        except Exception as e:
            self.logger.error(f"Deployment failed: {e}")
            return AgentResult(status="FAILED", errors=str(e), message="Deployment process failed.")
